export const ONLINE_STATE_CHANGE = "ONLINE_STATE_CHANGE";
export const CLEAR_DATA = "CLEAR_DATA";
export const ACCOUNT_STATE_CHANGE = "ACCOUNT_STATE_CHANGE";
export const GOING_ADMIN_STATE = "GOING_ADMIN_STATE";
